### ISSUE TITLE
periodicEtcdMembersHealthCheck function crashes when handling an empty endpoint

### ISSUE THREAD

**Issue by wongni** [mrajashree/etcdadm-controller#20]
A customer reported the following issue. 

_Initially the mgmt cluster had network connectivity issue that prevented the Kubernetes api server from working. There were also issue with Cilium. Eventually for some reason the ETCd cluster ending up having empty string in the `Status.endpoints` field which then crashes the controller for it._ 

```
2022-04-22T02:51:48.564Z        INFO    controllers.EtcdadmCluster      Member failed healthcheck, adding to unhealthy members list     {"member": ""}
2022-04-22T02:51:48.564Z        INFO    controllers.EtcdadmCluster      Machine for member does not exist       {"member": ""}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x183983a]
goroutine 239 [running]:
[github.com/mrajashree/etcdadm-controller/controllers.getEtcdMachineAddressFromClientURL](http://github.com/mrajashree/etcdadm-controller/controllers.getEtcdMachineAddressFromClientURL)(0x0, 0x0, 0xc00085b290, 0x0)
        [github.com/mrajashree/etcdadm-controller/controllers/helpers.go:187](http://github.com/mrajashree/etcdadm-controller/controllers/helpers.go:187) +0x3a
[github.com/mrajashree/etcdadm-controller/controllers](http://github.com/mrajashree/etcdadm-controller/controllers).(*EtcdadmClusterReconciler).periodicEtcdMembersHealthCheck(0xc000a07300, 0x1e64fb0, 0xc000a43fc0, 0xc000113180, 0xc000a0b340, 0xc00085b658, 0xc0001a1950, 0x24)
        [github.com/mrajashree/etcdadm-controller/controllers/periodic_healthcheck.go:148](http://github.com/mrajashree/etcdadm-controller/controllers/periodic_healthcheck.go:148) +0x53d
[github.com/mrajashree/etcdadm-controller/controllers](http://github.com/mrajashree/etcdadm-controller/controllers).(*EtcdadmClusterReconciler).startHealthCheckLoop(0xc000a07300, 0x1e64fb0, 0xc000a43fc0, 0xc000a36960)
        [github.com/mrajashree/etcdadm-controller/controllers/periodic_healthcheck.go:97](http://github.com/mrajashree/etcdadm-controller/controllers/periodic_healthcheck.go:97) +0x647
created by [github.com/mrajashree/etcdadm-controller/controllers](http://github.com/mrajashree/etcdadm-controller/controllers).(*EtcdadmClusterReconciler).SetupWithManager
        [github.com/mrajashree/etcdadm-controller/controllers/controller.go:82](http://github.com/mrajashree/etcdadm-controller/controllers/controller.go:82) +0x52b
```

**Comment by mrajashree** [comment]
Fix: https://github.com/mrajashree/etcdadm-controller/pull/21
